### ISSUE TITLE
Report error

### ISSUE THREAD

**Issue by RebeccaKirkwood** [cyrusinnovation/CodeTestBotApp#68]
When I click "generate report," sometime the "Cons:" section does not get separated from the "Pros" section. You can see this if you generate the report for the most recent Junior Ruby candidate that passed the test:

Developer 3 wrote:

Pros:

There are tests
Code shows understanding of good OO design principles (SoD, DRY, etc.) Cons:
Output is partially wrong
Multiple classes are defined in one file

**Comment by childss** [comment]
To whomever works on this: before going down any code rabbit holes, you might want to peek at the raw data to see if the assessment was formatted correctly when it was written. They're parsed as Markdown, more specifically as whatever the [marked](https://github.com/chjj/marked) default renderer expects. See [line 67 of the report controller](https://github.com/cyrusinnovation/CodeTestBotApp/blob/master/app/controllers/submission/report.js#L67).

Incorrect spacing around # symbols is the most likely culprit, IMO.

**Comment by RebeccaKirkwood** [comment]
Thanks for your feedback, Stuart. Hope all is well.

Best,
Rebecca

On Mon, Jan 26, 2015 at 5:00 PM, Stuart Childs <notifications@github.com>
wrote:

> To whomever works on this: before going down any code rabbit holes, you
> might want to peek at the raw data to see if the assessment was formatted
> correctly when it was written. They're parsed as Markdown, more
> specifically as whatever the marked <https://github.com/chjj/marked>
> default renderer expects. See line 67 of the report controller
> <https://github.com/cyrusinnovation/CodeTestBotApp/blob/master/app/controllers/submission/report.js#L67>
> .
>
> Incorrect spacing around # symbols is the most likely culprit, IMO.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyrusinnovation/CodeTestBotApp/issues/68#issuecomment-71547677>
> .
>



-- 
*Rebecca Kirkwood*
VP Human Resources
Cyrus Innovation <http://www.cyrusinnovation.com/>
Office: (212) 647-7186
Agile Software Development and Consulting
Crain's New York Best Places to Work 2012

**Comment by BenRKarl** [comment]
Stuart, indeed, in this case I discovered that there's an extra space after "Cons:" before the newline that must cause it to not be interpreted properly. I'll look into the best solution, perhaps we can easily strip improper spaces after "Pro" and "Con"
