### ISSUE TITLE
Edit email recipients of completed tests

### ISSUE THREAD

**Issue by RebeccaKirkwood** [cyrusinnovation/CodeTestBotApp#69]
Completed code tests are still being sent to Lacey and Stuart's email addresses. Can you remove? Does it make sense to send to the developers list-list instead?

**Comment by childss** [comment]
To save someone some time: you can change this by editing a config value on the Heroku instance (there are 2-3 env vars, like `NEW_ASSESSMENT_ADDRESS`). See https://github.com/cyrusinnovation/CodeTestBotServer/blob/master/app/mailers/submission_mailer.rb#L12

**Comment by RebeccaKirkwood** [comment]
you can change this by editing a config value on the Heroku instance (there are 2-3 env vars, like NEW_ASSESSMENT_ADDRESS). See https://github.com/cyrusinnovation/CodeTestBotServer/blob/master/app/mailers/submission_mailer.rb#L12

**Comment by AlabamaMike** [comment]
This is done.  Removed Stuart and Lacey, and updated Rebecca's email address.
